##spring:
##  security:
##    user:
##      name: Ajith
##      password: 12345
#
#spring:
#  datasource:
#    url: jdbc:mysql://springsecurity.cc0gkgd5jbqg.ap-south-1.rds.amazonaws.com/eazybank
#    username: Admin
#    password: Admin0416
#
#  jpa:
#    show-sql: true
#
#
#
#
